spring:
  application:
    name: reservas-api
  datasource:
    url: jdbc:h2:mem:turismodb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    addresses: rabbit-mq:5672
server:
  port: 4005
  servlet:
    context-path: /reservas
---
spring:  profiles:    active:    - development
  rabbitmq:    addresses: localhost:5672